// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/register.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	ServerName           string   `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	ServerInfo           *Server  `protobuf:"bytes,2,opt,name=serverInfo,proto3" json:"serverInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f68ee4285d3eaf, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *RegisterRequest) GetServerInfo() *Server {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

type RegisterResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f68ee4285d3eaf, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetAddrRequest struct {
	ServerName           string   `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddrRequest) Reset()         { *m = GetAddrRequest{} }
func (m *GetAddrRequest) String() string { return proto.CompactTextString(m) }
func (*GetAddrRequest) ProtoMessage()    {}
func (*GetAddrRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f68ee4285d3eaf, []int{2}
}

func (m *GetAddrRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddrRequest.Unmarshal(m, b)
}
func (m *GetAddrRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddrRequest.Marshal(b, m, deterministic)
}
func (m *GetAddrRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddrRequest.Merge(m, src)
}
func (m *GetAddrRequest) XXX_Size() int {
	return xxx_messageInfo_GetAddrRequest.Size(m)
}
func (m *GetAddrRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddrRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddrRequest proto.InternalMessageInfo

func (m *GetAddrRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

type Server struct {
	ServerIp             string   `protobuf:"bytes,1,opt,name=serverIp,proto3" json:"serverIp,omitempty"`
	ServerPort           string   `protobuf:"bytes,2,opt,name=serverPort,proto3" json:"serverPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f68ee4285d3eaf, []int{3}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetServerIp() string {
	if m != nil {
		return m.ServerIp
	}
	return ""
}

func (m *Server) GetServerPort() string {
	if m != nil {
		return m.ServerPort
	}
	return ""
}

type GetAddrResponse struct {
	Code                 int64     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ServerList           []*Server `protobuf:"bytes,3,rep,name=serverList,proto3" json:"serverList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetAddrResponse) Reset()         { *m = GetAddrResponse{} }
func (m *GetAddrResponse) String() string { return proto.CompactTextString(m) }
func (*GetAddrResponse) ProtoMessage()    {}
func (*GetAddrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f68ee4285d3eaf, []int{4}
}

func (m *GetAddrResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddrResponse.Unmarshal(m, b)
}
func (m *GetAddrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddrResponse.Marshal(b, m, deterministic)
}
func (m *GetAddrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddrResponse.Merge(m, src)
}
func (m *GetAddrResponse) XXX_Size() int {
	return xxx_messageInfo_GetAddrResponse.Size(m)
}
func (m *GetAddrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddrResponse proto.InternalMessageInfo

func (m *GetAddrResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAddrResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetAddrResponse) GetServerList() []*Server {
	if m != nil {
		return m.ServerList
	}
	return nil
}

type DeregisterRequest struct {
	ServerName           string   `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	ServerInfo           *Server  `protobuf:"bytes,2,opt,name=serverInfo,proto3" json:"serverInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeregisterRequest) Reset()         { *m = DeregisterRequest{} }
func (m *DeregisterRequest) String() string { return proto.CompactTextString(m) }
func (*DeregisterRequest) ProtoMessage()    {}
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f68ee4285d3eaf, []int{5}
}

func (m *DeregisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeregisterRequest.Unmarshal(m, b)
}
func (m *DeregisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeregisterRequest.Marshal(b, m, deterministic)
}
func (m *DeregisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeregisterRequest.Merge(m, src)
}
func (m *DeregisterRequest) XXX_Size() int {
	return xxx_messageInfo_DeregisterRequest.Size(m)
}
func (m *DeregisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeregisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeregisterRequest proto.InternalMessageInfo

func (m *DeregisterRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *DeregisterRequest) GetServerInfo() *Server {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

type DeregisterResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeregisterResponse) Reset()         { *m = DeregisterResponse{} }
func (m *DeregisterResponse) String() string { return proto.CompactTextString(m) }
func (*DeregisterResponse) ProtoMessage()    {}
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7f68ee4285d3eaf, []int{6}
}

func (m *DeregisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeregisterResponse.Unmarshal(m, b)
}
func (m *DeregisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeregisterResponse.Marshal(b, m, deterministic)
}
func (m *DeregisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeregisterResponse.Merge(m, src)
}
func (m *DeregisterResponse) XXX_Size() int {
	return xxx_messageInfo_DeregisterResponse.Size(m)
}
func (m *DeregisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeregisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeregisterResponse proto.InternalMessageInfo

func (m *DeregisterResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeregisterResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "proto.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "proto.RegisterResponse")
	proto.RegisterType((*GetAddrRequest)(nil), "proto.GetAddrRequest")
	proto.RegisterType((*Server)(nil), "proto.Server")
	proto.RegisterType((*GetAddrResponse)(nil), "proto.GetAddrResponse")
	proto.RegisterType((*DeregisterRequest)(nil), "proto.DeregisterRequest")
	proto.RegisterType((*DeregisterResponse)(nil), "proto.DeregisterResponse")
}

func init() { proto.RegisterFile("proto/register.proto", fileDescriptor_d7f68ee4285d3eaf) }

var fileDescriptor_d7f68ee4285d3eaf = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x4d, 0xad, 0x22, 0x8c, 0x51, 0x70, 0xa2, 0x58, 0x7b, 0x30, 0xcd, 0x9e, 0xb8, 0x88, 0x06,
	0x2f, 0x44, 0x4f, 0x24, 0x24, 0xc6, 0xc4, 0x18, 0xb3, 0xfe, 0x80, 0x62, 0x07, 0xc2, 0x01, 0xb6,
	0xee, 0xae, 0x7e, 0xa1, 0x1f, 0x66, 0xd8, 0x0e, 0xec, 0x0a, 0x9a, 0xd8, 0x83, 0xa7, 0xce, 0xce,
	0x7b, 0x7d, 0xef, 0xf5, 0x6d, 0xe1, 0xa8, 0xd0, 0xca, 0xaa, 0x0b, 0x4d, 0x93, 0xa9, 0xb1, 0xa4,
	0xbb, 0xee, 0x88, 0x3b, 0xee, 0x21, 0x9e, 0xa1, 0x29, 0x19, 0x90, 0xf4, 0xf6, 0x4e, 0xc6, 0xe2,
	0x19, 0x80, 0x21, 0xfd, 0x41, 0xfa, 0xe1, 0x65, 0x46, 0x49, 0x94, 0x45, 0x9d, 0x86, 0x0c, 0x36,
	0x78, 0xbe, 0xc4, 0xef, 0xe6, 0x63, 0x95, 0x6c, 0x65, 0x51, 0x67, 0xaf, 0xb7, 0x5f, 0xaa, 0x76,
	0x9f, 0x1c, 0x20, 0x03, 0x82, 0xe8, 0x43, 0xcb, 0x3b, 0x98, 0x42, 0xcd, 0x0d, 0x21, 0xc2, 0xf6,
	0xab, 0xca, 0x4b, 0xf1, 0x58, 0xba, 0x19, 0x5b, 0x10, 0xcf, 0xcc, 0xc4, 0xe9, 0x35, 0xe4, 0x62,
	0x14, 0x97, 0x70, 0x70, 0x4b, 0x76, 0x90, 0xe7, 0x7f, 0x8d, 0x26, 0x86, 0x50, 0x2b, 0x13, 0x60,
	0x0a, 0x75, 0xce, 0x50, 0x30, 0x6f, 0x75, 0xf6, 0x2a, 0x8f, 0x4a, 0x5b, 0x36, 0x0c, 0x36, 0x62,
	0x0c, 0xcd, 0x95, 0x6f, 0x95, 0xc0, 0xbe, 0x99, 0xfb, 0xa9, 0xb1, 0x49, 0x9c, 0xc5, 0xbf, 0x36,
	0xb3, 0x20, 0x88, 0x11, 0x1c, 0x0e, 0x49, 0xff, 0x6f, 0xfb, 0xd7, 0x80, 0xa1, 0x47, 0x95, 0xcf,
	0xe9, 0x7d, 0x46, 0x50, 0x5f, 0x5e, 0x1d, 0xde, 0x04, 0x73, 0x9b, 0xfd, 0xd6, 0xfe, 0x9c, 0xf4,
	0x64, 0x63, 0xcf, 0x7e, 0x7d, 0xd8, 0xe5, 0x46, 0xf1, 0x98, 0x39, 0xdf, 0x6f, 0x36, 0x6d, 0xaf,
	0xaf, 0xf9, 0xcd, 0x01, 0x80, 0xcf, 0x8f, 0x09, 0xb3, 0x36, 0x6a, 0x4b, 0x4f, 0x7f, 0x40, 0x4a,
	0x89, 0x51, 0xcd, 0x21, 0x57, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x87, 0x93, 0x40, 0x39, 0x08,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegisterClient is the client API for Register service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegisterClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetAddr(ctx context.Context, in *GetAddrRequest, opts ...grpc.CallOption) (*GetAddrResponse, error)
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error)
}

type registerClient struct {
	cc *grpc.ClientConn
}

func NewRegisterClient(cc *grpc.ClientConn) RegisterClient {
	return &registerClient{cc}
}

func (c *registerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/proto.Register/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerClient) GetAddr(ctx context.Context, in *GetAddrRequest, opts ...grpc.CallOption) (*GetAddrResponse, error) {
	out := new(GetAddrResponse)
	err := c.cc.Invoke(ctx, "/proto.Register/GetAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error) {
	out := new(DeregisterResponse)
	err := c.cc.Invoke(ctx, "/proto.Register/Deregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterServer is the server API for Register service.
type RegisterServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	GetAddr(context.Context, *GetAddrRequest) (*GetAddrResponse, error)
	Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error)
}

// UnimplementedRegisterServer can be embedded to have forward compatible implementations.
type UnimplementedRegisterServer struct {
}

func (*UnimplementedRegisterServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedRegisterServer) GetAddr(ctx context.Context, req *GetAddrRequest) (*GetAddrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddr not implemented")
}
func (*UnimplementedRegisterServer) Deregister(ctx context.Context, req *DeregisterRequest) (*DeregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deregister not implemented")
}

func RegisterRegisterServer(s *grpc.Server, srv RegisterServer) {
	s.RegisterService(&_Register_serviceDesc, srv)
}

func _Register_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Register/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Register_GetAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).GetAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Register/GetAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).GetAddr(ctx, req.(*GetAddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Register_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Register/Deregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).Deregister(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Register_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Register",
	HandlerType: (*RegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Register_Register_Handler,
		},
		{
			MethodName: "GetAddr",
			Handler:    _Register_GetAddr_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _Register_Deregister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/register.proto",
}
